version: "3.8"

services: 
  # Database policies
  database: 
    restart: on-failure
    image: mariadb:10.3.35
    command: --init-file /usr/lib/bin/mysql/dbinit.sql
    volumes: 
      - ./assets/build/dbinit.sql:/usr/lib/bin/mysql/dbinit.sql
    env_file:
      - '.env'
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - default

  api:
    build:
      context: .
      dockerfile: /home/jannick/Desktop/Dynamic-TS-swagger-API/API.Dockerfile
    ports: 
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - database
    links:
      - "database"
    networks:
      - default