
export type IHTTPMimeType = "audio/aac"|"application/x-abiword"|"application/x-freearc"|"image/avif"|"video/x-msvideo"|"application/vnd.amazon.ebook"
                            |"image/bmp"|"application/x-bzip"|"application/x-bzip2"|"application/x-cdf"|"application/x-csh"|"text/css"|"test/csv"
                            |"application/msword"|"application/msword"|"application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                            |"application/vnd.ms-fontobject"|"application/epub+zip"|"application/gzip"|"image/gif"|"text/html"
                            |"image/vnd.microsoft.icon"|"text/calendar"|"application/java-archive"|"image/jpeg"|"text/javascript"
                            |"application/json"|"application/1d+json"|"audio/midi"|"audio/x-midi"|"audio/mpeg"|"video/mp4"|"video/mpeg"
                            |"application/vnc.apple.installer+xml"|"application/vnd.oasis.opendocument.presentation"|"application/vnd.oasis.opendocument.spreadsheet"
                            |"application/vnd.oasis.opendocument.text"|"audio/ogg"|"video/ogg"|"application/ogg"|"audio/opus"|"font/otf"|"image/png"
                            |"application/pdf"|"application/x-httpd-php"|"application/vnd.ms-powerpoint"
                            |"application/vnd.openxmlformats-officedocument.presentationml.presentation"|"application/vnd.rar"|"application/rtf"
                            |"application/x-sh"|"image/svg+xml"|"application/x-tar"|"image/tiff"|"video/mp2t"|"font/ttf"|"texxt/plain"|"application/vnd.visio"
                            |"audio/wav"|"audio/webm"|"video/webm"|"image/webp"|"font/woff"|"font/woff2"|"application/xhtml+xml"|"application/vnd.ms-exel"
                            |"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"|"application/xml"|"text/xml"|"application/atom/xml"
                            |"application/vnd.mozilla.xul+xml"|"application/zip"|"video/3gpp"|"audio/3gpp"|"video/3gpp2"|"audio/3gpp2"
                            |"application/x-7z-compressed";